---
## Ansible Playbook install AuditD Daemon on Debian Systems
- name: Install AuditD and Laurel for Wazuh on Debian/Ubuntu Systems
  hosts: Hosts
  tasks:
    - name: Check if auditd.service exists
      ansible.builtin.stat:
        path: /etc/systemd/system/multi-user.target.wants/auditd.service
      register: auditd_service

    - name: Check if laurel.conf exists
      ansible.builtin.stat:
        path: /etc/audit/plugins.d/laurel.conf
      register: laurel
      when: auditd_service.stat.exists

    - name: Block AuditD installation
      when: not auditd_service.stat.exists
      block:
        - name: Install AuditD
          ansible.builtin.apt:
            name: auditd
            state: present

        - name: Create /etc/audit/laurel directory
          ansible.builtin.file:
            path: /etc/audit/laurel
            state: directory
            mode: '0755'

    - name: Install laurel if not exists
      when: not laurel.stat.exists
      block:
        - name: Create _laurel user
          ansible.builtin.user:
            name: _laurel
            system: true
            home: /var/log/laurel
            shell: /bin/sh

        - name: Download laurel-v0.5.5-x86_64-glibc.tar.gz
          ansible.builtin.get_url:
            url: https://github.com/threathunters-io/laurel/releases/download/v0.5.5/laurel-v0.5.5-x86_64-glibc.tar.gz
            dest: /tmp
            mode: '0644'

        - name: Unarchive laurel-v0.5.5-x86_64-glibc.tar.gz
          ansible.builtin.unarchive:
            src: /tmp/laurel-v0.5.5-x86_64-glibc.tar.gz
            dest: /tmp

        - name: Install laurel if not exists
          ansible.builtin.command: install -m 755 /tmp/laurel /usr/local/sbin/laurel
          changed_when: not (laurel.stat.exists and laurel.stat.isreg)

        - name: Copy laurel.conf to /etc/audit/laurel
          ansible.builtin.copy:
            src: ~/github/ansible/files/auditd/laurel/config.toml
            dest: /etc/audit/laurel/config.toml
            owner: root
            group: root
            mode: '0644'

        - name: Copy config.toml to /etc/audit/plugins.d
          ansible.builtin.copy:
            src: ~/github/ansible/files/auditd/plugins.d/laurel.conf
            dest: /etc/audit/plugins.d/laurel.conf
            owner: root
            group: root
            mode: '0644'

    - name: Restart auditd service
      ansible.builtin.service:
        name: auditd
        state: restarted
      when:
        - not auditd_service.stat.exists
        - not laurel.stat.exists
